
import React from "react";
import { motion } from "framer-motion";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";

const faqs = [
  {
    question: "What is BikinKonten.ai?",
    answer: "BikinKonten.ai is an AI-powered digital marketing solution developed by PT Aira Teknologi Indonesia. It helps businesses create high-quality content, optimize marketing campaigns, and improve their digital presence through advanced artificial intelligence technology."
  },
  {
    question: "How does the AI content generation work?",
    answer: "Our AI analyzes your brand voice, target audience, and marketing objectives to generate relevant, engaging content. It uses advanced natural language processing to create human-like text that resonates with your audience while maintaining your brand's unique style and tone."
  },
  {
    question: "Is the content created by BikinKonten.ai original?",
    answer: "Yes, all content generated by BikinKonten.ai is original and created specifically for your brand. Our AI doesn't copy existing content but rather creates new content based on your requirements and guidelines. You can also customize and edit the generated content as needed."
  },
  {
    question: "Can BikinKonten.ai integrate with my existing marketing tools?",
    answer: "Absolutely! BikinKonten.ai is designed to integrate seamlessly with popular marketing platforms, CMS systems, social media channels, and analytics tools. We offer API access for custom integrations on our Enterprise plan."
  },
  {
    question: "Do I need technical knowledge to use BikinKonten.ai?",
    answer: "No technical knowledge is required. BikinKonten.ai features an intuitive, user-friendly interface designed for marketers of all skill levels. Our platform guides you through the process with clear instructions and helpful tooltips."
  },
  {
    question: "How long does the free trial last?",
    answer: "Our free trial lasts for 14 days, giving you ample time to explore the platform's features and capabilities. No credit card is required to start your trial, and you can cancel anytime without any obligation."
  },
  {
    question: "Can I upgrade or downgrade my plan later?",
    answer: "Yes, you can easily upgrade or downgrade your subscription plan at any time through your account dashboard. When upgrading, you'll immediately gain access to additional features. When downgrading, the changes will take effect at the start of your next billing cycle."
  },
  {
    question: "Is my data secure with BikinKonten.ai?",
    answer: "We take data security very seriously. BikinKonten.ai employs industry-standard encryption, secure data storage, and strict access controls to protect your information. We are compliant with relevant data protection regulations and never share your data with third parties without your explicit consent."
  }
];

const FAQSection = () => {
  return (
    <section id="faq" className="py-20 bg-gray-50 dark:bg-gray-900 relative overflow-hidden">
      {/* Background elements */}
      <div className="absolute top-0 left-0 w-full h-full bg-dots opacity-50 -z-10"></div>
      <div className="absolute top-1/4 -right-64 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl -z-10"></div>
      <div className="absolute bottom-1/4 -left-64 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl -z-10"></div>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center max-w-3xl mx-auto mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-400">
            Find answers to common questions about BikinKonten.ai and how it can help your business.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="max-w-3xl mx-auto"
        >
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left font-medium">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-gray-600 dark:text-gray-400">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
        
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-16 text-center"
        >
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            Still have questions? We're here to help.
          </p>
          <div className="inline-flex items-center justify-center rounded-md bg-blue-50 dark:bg-blue-900/20 px-6 py-3">
            <span className="text-blue-700 dark:text-blue-300 font-medium">
              Contact our support team at support@bikinkonten.ai
            </span>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default FAQSection;
